### ISSUE TITLE
Filter Inputs - support 2 styles

### ISSUE THREAD

**Issue by Fosome** [vigetlabs/active_material#20]
A little background:

Typically ActiveAdmin + Ransack make index filters look like this for strings:

![screen shot 2016-03-10 at 8 33 45 am](https://cloud.githubusercontent.com/assets/842652/13674617/6fad9f02-e69b-11e5-978d-646168ac83d4.png)

for this code:

`filter :name`

---

You can force ActiveAdmin to use one style, like contains, for the filter with this:

`filter :name_cont`

Which produces a filter *without select/text input combo*. Like this:

![screen shot 2016-03-10 at 8 41 06 am](https://cloud.githubusercontent.com/assets/842652/13674721/dadf0f22-e69b-11e5-8227-7728e43d775f.png)

---

Is it possible to style both to look great together and alone?

**Comment by nhunzaker** [comment]
Hmm. We should be smarter about how we apply the border-radius to the left-hand side of that second example. That would improve the appearance greatly.

**Comment by ten1seven** [comment]
Is it a simple select next to a text input? Could it be solved with:

```css
select + input[type="text"] {
   border-left-width: 0;
   border-bottom-left-radius: 0;
   border-top-left-radius: 0;
}
```
