### ISSUE TITLE
Header scope 

### ISSUE THREAD

**Issue by irmela** [vigetlabs/active_material#44]
As part of `app/assets/stylesheets/active_material/components/header.scss` we include toolbar styling for `.header`. This leads to problems for example when there are other elements with a `header` class (in my case a table header). What do you think about applying the styling to `#header` instead of `.header`?

### Current
```css
.header {
  @include am-toolbar;
  @include am-toolbar-primary;
  padding-right: am-unit(8);
}
```

### Improved
```css
#header {
  @include am-toolbar;
  @include am-toolbar-primary;
  padding-right: am-unit(8);
}
```
